# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpringApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpringApp
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON'

end
